select
  id_orden_servicio,
  id_reserva_credito,
  id_cuenta_credito,
  id_cliente,
  id_contrato,
  id_tarifa_detalle,
  id_sucursal_origen,
  id_sucursal_destino,
  id_ruta,
  {{ date_key('fecha_creacion') }} as id_fecha_creacion_orden,
  {{ date_key('vigencia_hasta') }} as id_fecha_vigencia_orden,
  {{ date_key('fecha_primer_envio') }} as id_fecha_primer_envio,
  {{ date_key('fecha_ultimo_envio') }} as id_fecha_ultimo_envio,
  {{ date_key('fecha_primer_compromiso_recojo') }} as id_fecha_primer_compromiso_recojo,
  {{ date_key('fecha_ultimo_compromiso_recojo') }} as id_fecha_ultimo_compromiso_recojo,
  {{ date_key('fecha_ultimo_cierre_envio') }} as id_fecha_ultimo_cierre_envio,
  1 as cantidad_ordenes,
  coalesce(cantidad_envios, 0) as cantidad_envios,
  case when id_tarifa_detalle = 0 then 1 else 0 end as precio_manual_flag,
  {{ boolean_flag("estado_orden = 'APROBADA'") }} as orden_aprobada_flag,
  {{ boolean_flag("cantidad_envios > 0") }} as envio_generado_flag,
  {{ boolean_flag("tiene_envio_cerrado_flag = 1") }} as envio_cerrado_flag,
  {{ boolean_flag("estado_orden = 'VENCIDA' and cantidad_envios = 0") }} as orden_vencida_sin_envio_flag,
  {{ boolean_flag("tiene_devolucion_flag = 1") }} as devuelto_flag,
  {{ boolean_flag("coalesce(monto_facturado_bob, 0) > 0") }} as facturado_flag,
  coalesce(total_bob, 0) as total_orden_bob,
  coalesce(monto_reservado_bob, 0) as monto_reservado_bob,
  limite_credito_bob as limite_credito_bob_snapshot,
  saldo_utilizado_bob as saldo_utilizado_bob_snapshot,
  saldo_vencido_bob as saldo_vencido_bob_snapshot,
  credito_disponible_bob as credito_disponible_bob_snapshot,
  coalesce(monto_facturado_bob, 0) as monto_facturado_bob,
  coalesce(cantidad_lineas_facturadas, 0) as cantidad_lineas_facturadas
from {{ ref('int_orden_servicio_base') }}
