select
  id_envio,
  id_orden_servicio,
  id_reserva_credito,
  id_cuenta_credito,
  id_cliente,
  id_tarifa_detalle,
  id_sucursal_origen,
  id_sucursal_destino,
  id_ruta,
  coalesce(estado_final_codigo, 'NO_DEFINIDO') as id_estado_envio,
  {{ date_key('fecha_creacion') }} as id_fecha_creacion_orden,
  {{ date_key('vigencia_hasta') }} as id_fecha_vigencia_orden,
  {{ date_key('fecha_registro') }} as id_fecha_registro_envio,
  {{ date_key('fecha_compromiso_listo_recojo') }} as id_fecha_compromiso_recojo,
  {{ date_key('fecha_cierre_envio') }} as id_fecha_cierre_envio,
  1 as cantidad_envios,
  {{ boolean_flag("estado_orden = 'APROBADA'") }} as orden_aprobada_flag,
  1 as envio_generado_flag,
  {{ boolean_flag("fecha_cierre_envio is not null") }} as envio_cerrado_flag,
  {{ boolean_flag("fecha_cumplimiento_sla is not null and fecha_compromiso_listo_recojo is not null and fecha_cumplimiento_sla <= fecha_compromiso_listo_recojo") }} as cumple_sla_recojo_flag,
  {{ boolean_flag("estado_final_codigo = 'DEVUELTO'") }} as devuelto_flag,
  {{ boolean_flag("coalesce(monto_facturado_bob, 0) > 0") }} as facturado_flag,
  coalesce(peso_kg, 0) as peso_envio_kg,
  coalesce(volumen_m3, 0) as volumen_envio_m3,
  coalesce(valor_declarado_bob, 0) as valor_declarado_bob,
  coalesce(datediff('hour', fecha_creacion, fecha_registro), 0) as horas_orden_a_envio,
  coalesce(datediff('hour', fecha_creacion, fecha_cierre_envio), 0) as tiempo_ciclo_horas,
  coalesce(datediff('hour', fecha_compromiso_listo_recojo, fecha_cumplimiento_sla), 0) as desviacion_sla_horas,
  coalesce(monto_facturado_bob, 0) as monto_facturado_bob,
  coalesce(cantidad_lineas_facturadas, 0) as cantidad_lineas_facturadas
from {{ ref('int_envio_base') }}
