-- =============================================================================
-- SNOWFLAKE BOOTSTRAP
-- PROYECTO_BI_TRANSPORTE_V2
-- =============================================================================
--
-- Objetivo:
-- 1. Crear warehouse, base y esquemas raw/DWH
-- 2. Crear roles separados para:
--    - Carga RAW desde Airbyte
--    - Transformacion dbt
--    - Lectura BI
-- 3. Crear usuarios dedicados
-- 4. Dejar permisos futuros para evitar fallas cuando lleguen nuevas tablas
-- 5. Dejar politica de red opcional para restringir IPs
--
-- Ejecutar con un rol administrativo alto, por ejemplo ACCOUNTADMIN.
-- Reemplazar passwords e IPs antes de ejecutar en produccion.
-- =============================================================================


-- =============================================================================
-- 0) CONTEXTO
-- =============================================================================
USE ROLE ACCOUNTADMIN;


-- =============================================================================
-- 1) NOMBRES DEL NUEVO ENTORNO
-- =============================================================================
-- Warehouse:
--   WH_PROYECTO_BI_TRANSPORTE_V2
--
-- Database:
--   PROYECTO_BI_TRANSPORTE_V2
--
-- Roles:
--   ROLE_AIRBYTE_RAW_PROYECTO_BI_TRANSPORTE_V2
--   ROLE_DBT_PROYECTO_BI_TRANSPORTE_V2
--   ROLE_BI_READ_PROYECTO_BI_TRANSPORTE_V2
--
-- Usuarios:
--   USR_AIRBYTE_PROYECTO_BI_TRANSPORTE_V2
--   USR_DBT_PROYECTO_BI_TRANSPORTE_V2
--   USR_BI_PROYECTO_BI_TRANSPORTE_V2


-- =============================================================================
-- 2) WAREHOUSE
-- =============================================================================
CREATE WAREHOUSE IF NOT EXISTS WH_PROYECTO_BI_TRANSPORTE_V2
WITH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;


-- =============================================================================
-- 3) DATABASE Y SCHEMAS
-- =============================================================================
CREATE DATABASE IF NOT EXISTS PROYECTO_BI_TRANSPORTE_V2;

USE DATABASE PROYECTO_BI_TRANSPORTE_V2;

-- RAW LANDING
CREATE SCHEMA IF NOT EXISTS MYSQL_COMERCIAL;
CREATE SCHEMA IF NOT EXISTS PG_OPS;
CREATE SCHEMA IF NOT EXISTS SQLSERVER_FIN;
CREATE SCHEMA IF NOT EXISTS MONGO_TELEMETRIA;

-- TRANSFORMACION / CONSUMO
CREATE SCHEMA IF NOT EXISTS DWH_DEV;
CREATE SCHEMA IF NOT EXISTS SNAPSHOTS_DWH;


-- =============================================================================
-- 4) ROLES
-- =============================================================================
CREATE ROLE IF NOT EXISTS ROLE_AIRBYTE_RAW_PROYECTO_BI_TRANSPORTE_V2;
CREATE ROLE IF NOT EXISTS ROLE_DBT_PROYECTO_BI_TRANSPORTE_V2;
CREATE ROLE IF NOT EXISTS ROLE_BI_READ_PROYECTO_BI_TRANSPORTE_V2;


-- =============================================================================
-- 5) PERMISOS DE WAREHOUSE
-- =============================================================================
GRANT USAGE, OPERATE ON WAREHOUSE WH_PROYECTO_BI_TRANSPORTE_V2
  TO ROLE ROLE_AIRBYTE_RAW_PROYECTO_BI_TRANSPORTE_V2;

GRANT USAGE, OPERATE ON WAREHOUSE WH_PROYECTO_BI_TRANSPORTE_V2
  TO ROLE ROLE_DBT_PROYECTO_BI_TRANSPORTE_V2;

GRANT USAGE ON WAREHOUSE WH_PROYECTO_BI_TRANSPORTE_V2
  TO ROLE ROLE_BI_READ_PROYECTO_BI_TRANSPORTE_V2;


-- =============================================================================
-- 6) PERMISOS DE DATABASE
-- =============================================================================
GRANT USAGE ON DATABASE PROYECTO_BI_TRANSPORTE_V2
  TO ROLE ROLE_AIRBYTE_RAW_PROYECTO_BI_TRANSPORTE_V2;

GRANT USAGE ON DATABASE PROYECTO_BI_TRANSPORTE_V2
  TO ROLE ROLE_DBT_PROYECTO_BI_TRANSPORTE_V2;

GRANT USAGE ON DATABASE PROYECTO_BI_TRANSPORTE_V2
  TO ROLE ROLE_BI_READ_PROYECTO_BI_TRANSPORTE_V2;


-- =============================================================================
-- 7) ROLE AIRBYTE RAW
--    Solo carga y administra objetos dentro de RAW
-- =============================================================================
GRANT USAGE ON SCHEMA PROYECTO_BI_TRANSPORTE_V2.MYSQL_COMERCIAL
  TO ROLE ROLE_AIRBYTE_RAW_PROYECTO_BI_TRANSPORTE_V2;
GRANT USAGE ON SCHEMA PROYECTO_BI_TRANSPORTE_V2.PG_OPS
  TO ROLE ROLE_AIRBYTE_RAW_PROYECTO_BI_TRANSPORTE_V2;
GRANT USAGE ON SCHEMA PROYECTO_BI_TRANSPORTE_V2.SQLSERVER_FIN
  TO ROLE ROLE_AIRBYTE_RAW_PROYECTO_BI_TRANSPORTE_V2;
GRANT USAGE ON SCHEMA PROYECTO_BI_TRANSPORTE_V2.MONGO_TELEMETRIA
  TO ROLE ROLE_AIRBYTE_RAW_PROYECTO_BI_TRANSPORTE_V2;

GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT
  ON SCHEMA PROYECTO_BI_TRANSPORTE_V2.MYSQL_COMERCIAL
  TO ROLE ROLE_AIRBYTE_RAW_PROYECTO_BI_TRANSPORTE_V2;
GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT
  ON SCHEMA PROYECTO_BI_TRANSPORTE_V2.PG_OPS
  TO ROLE ROLE_AIRBYTE_RAW_PROYECTO_BI_TRANSPORTE_V2;
GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT
  ON SCHEMA PROYECTO_BI_TRANSPORTE_V2.SQLSERVER_FIN
  TO ROLE ROLE_AIRBYTE_RAW_PROYECTO_BI_TRANSPORTE_V2;
GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT
  ON SCHEMA PROYECTO_BI_TRANSPORTE_V2.MONGO_TELEMETRIA
  TO ROLE ROLE_AIRBYTE_RAW_PROYECTO_BI_TRANSPORTE_V2;

GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES
  ON ALL TABLES IN SCHEMA PROYECTO_BI_TRANSPORTE_V2.MYSQL_COMERCIAL
  TO ROLE ROLE_AIRBYTE_RAW_PROYECTO_BI_TRANSPORTE_V2;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES
  ON ALL TABLES IN SCHEMA PROYECTO_BI_TRANSPORTE_V2.PG_OPS
  TO ROLE ROLE_AIRBYTE_RAW_PROYECTO_BI_TRANSPORTE_V2;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES
  ON ALL TABLES IN SCHEMA PROYECTO_BI_TRANSPORTE_V2.SQLSERVER_FIN
  TO ROLE ROLE_AIRBYTE_RAW_PROYECTO_BI_TRANSPORTE_V2;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES
  ON ALL TABLES IN SCHEMA PROYECTO_BI_TRANSPORTE_V2.MONGO_TELEMETRIA
  TO ROLE ROLE_AIRBYTE_RAW_PROYECTO_BI_TRANSPORTE_V2;

GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES
  ON FUTURE TABLES IN SCHEMA PROYECTO_BI_TRANSPORTE_V2.MYSQL_COMERCIAL
  TO ROLE ROLE_AIRBYTE_RAW_PROYECTO_BI_TRANSPORTE_V2;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES
  ON FUTURE TABLES IN SCHEMA PROYECTO_BI_TRANSPORTE_V2.PG_OPS
  TO ROLE ROLE_AIRBYTE_RAW_PROYECTO_BI_TRANSPORTE_V2;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES
  ON FUTURE TABLES IN SCHEMA PROYECTO_BI_TRANSPORTE_V2.SQLSERVER_FIN
  TO ROLE ROLE_AIRBYTE_RAW_PROYECTO_BI_TRANSPORTE_V2;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES
  ON FUTURE TABLES IN SCHEMA PROYECTO_BI_TRANSPORTE_V2.MONGO_TELEMETRIA
  TO ROLE ROLE_AIRBYTE_RAW_PROYECTO_BI_TRANSPORTE_V2;

GRANT SELECT ON ALL VIEWS IN SCHEMA PROYECTO_BI_TRANSPORTE_V2.MYSQL_COMERCIAL
  TO ROLE ROLE_AIRBYTE_RAW_PROYECTO_BI_TRANSPORTE_V2;
GRANT SELECT ON ALL VIEWS IN SCHEMA PROYECTO_BI_TRANSPORTE_V2.PG_OPS
  TO ROLE ROLE_AIRBYTE_RAW_PROYECTO_BI_TRANSPORTE_V2;
GRANT SELECT ON ALL VIEWS IN SCHEMA PROYECTO_BI_TRANSPORTE_V2.SQLSERVER_FIN
  TO ROLE ROLE_AIRBYTE_RAW_PROYECTO_BI_TRANSPORTE_V2;
GRANT SELECT ON ALL VIEWS IN SCHEMA PROYECTO_BI_TRANSPORTE_V2.MONGO_TELEMETRIA
  TO ROLE ROLE_AIRBYTE_RAW_PROYECTO_BI_TRANSPORTE_V2;

GRANT SELECT ON FUTURE VIEWS IN SCHEMA PROYECTO_BI_TRANSPORTE_V2.MYSQL_COMERCIAL
  TO ROLE ROLE_AIRBYTE_RAW_PROYECTO_BI_TRANSPORTE_V2;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA PROYECTO_BI_TRANSPORTE_V2.PG_OPS
  TO ROLE ROLE_AIRBYTE_RAW_PROYECTO_BI_TRANSPORTE_V2;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA PROYECTO_BI_TRANSPORTE_V2.SQLSERVER_FIN
  TO ROLE ROLE_AIRBYTE_RAW_PROYECTO_BI_TRANSPORTE_V2;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA PROYECTO_BI_TRANSPORTE_V2.MONGO_TELEMETRIA
  TO ROLE ROLE_AIRBYTE_RAW_PROYECTO_BI_TRANSPORTE_V2;


-- =============================================================================
-- 8) ROLE DBT
--    Lee RAW y escribe DWH_DEV + SNAPSHOTS_DWH
-- =============================================================================
GRANT USAGE ON SCHEMA PROYECTO_BI_TRANSPORTE_V2.MYSQL_COMERCIAL
  TO ROLE ROLE_DBT_PROYECTO_BI_TRANSPORTE_V2;
GRANT USAGE ON SCHEMA PROYECTO_BI_TRANSPORTE_V2.PG_OPS
  TO ROLE ROLE_DBT_PROYECTO_BI_TRANSPORTE_V2;
GRANT USAGE ON SCHEMA PROYECTO_BI_TRANSPORTE_V2.SQLSERVER_FIN
  TO ROLE ROLE_DBT_PROYECTO_BI_TRANSPORTE_V2;
GRANT USAGE ON SCHEMA PROYECTO_BI_TRANSPORTE_V2.MONGO_TELEMETRIA
  TO ROLE ROLE_DBT_PROYECTO_BI_TRANSPORTE_V2;
GRANT USAGE ON SCHEMA PROYECTO_BI_TRANSPORTE_V2.DWH_DEV
  TO ROLE ROLE_DBT_PROYECTO_BI_TRANSPORTE_V2;
GRANT USAGE ON SCHEMA PROYECTO_BI_TRANSPORTE_V2.SNAPSHOTS_DWH
  TO ROLE ROLE_DBT_PROYECTO_BI_TRANSPORTE_V2;

GRANT SELECT ON ALL TABLES IN SCHEMA PROYECTO_BI_TRANSPORTE_V2.MYSQL_COMERCIAL
  TO ROLE ROLE_DBT_PROYECTO_BI_TRANSPORTE_V2;
GRANT SELECT ON ALL TABLES IN SCHEMA PROYECTO_BI_TRANSPORTE_V2.PG_OPS
  TO ROLE ROLE_DBT_PROYECTO_BI_TRANSPORTE_V2;
GRANT SELECT ON ALL TABLES IN SCHEMA PROYECTO_BI_TRANSPORTE_V2.SQLSERVER_FIN
  TO ROLE ROLE_DBT_PROYECTO_BI_TRANSPORTE_V2;
GRANT SELECT ON ALL TABLES IN SCHEMA PROYECTO_BI_TRANSPORTE_V2.MONGO_TELEMETRIA
  TO ROLE ROLE_DBT_PROYECTO_BI_TRANSPORTE_V2;

GRANT SELECT ON FUTURE TABLES IN SCHEMA PROYECTO_BI_TRANSPORTE_V2.MYSQL_COMERCIAL
  TO ROLE ROLE_DBT_PROYECTO_BI_TRANSPORTE_V2;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PROYECTO_BI_TRANSPORTE_V2.PG_OPS
  TO ROLE ROLE_DBT_PROYECTO_BI_TRANSPORTE_V2;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PROYECTO_BI_TRANSPORTE_V2.SQLSERVER_FIN
  TO ROLE ROLE_DBT_PROYECTO_BI_TRANSPORTE_V2;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PROYECTO_BI_TRANSPORTE_V2.MONGO_TELEMETRIA
  TO ROLE ROLE_DBT_PROYECTO_BI_TRANSPORTE_V2;

GRANT SELECT ON ALL VIEWS IN SCHEMA PROYECTO_BI_TRANSPORTE_V2.MYSQL_COMERCIAL
  TO ROLE ROLE_DBT_PROYECTO_BI_TRANSPORTE_V2;
GRANT SELECT ON ALL VIEWS IN SCHEMA PROYECTO_BI_TRANSPORTE_V2.PG_OPS
  TO ROLE ROLE_DBT_PROYECTO_BI_TRANSPORTE_V2;
GRANT SELECT ON ALL VIEWS IN SCHEMA PROYECTO_BI_TRANSPORTE_V2.SQLSERVER_FIN
  TO ROLE ROLE_DBT_PROYECTO_BI_TRANSPORTE_V2;
GRANT SELECT ON ALL VIEWS IN SCHEMA PROYECTO_BI_TRANSPORTE_V2.MONGO_TELEMETRIA
  TO ROLE ROLE_DBT_PROYECTO_BI_TRANSPORTE_V2;

GRANT SELECT ON FUTURE VIEWS IN SCHEMA PROYECTO_BI_TRANSPORTE_V2.MYSQL_COMERCIAL
  TO ROLE ROLE_DBT_PROYECTO_BI_TRANSPORTE_V2;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA PROYECTO_BI_TRANSPORTE_V2.PG_OPS
  TO ROLE ROLE_DBT_PROYECTO_BI_TRANSPORTE_V2;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA PROYECTO_BI_TRANSPORTE_V2.SQLSERVER_FIN
  TO ROLE ROLE_DBT_PROYECTO_BI_TRANSPORTE_V2;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA PROYECTO_BI_TRANSPORTE_V2.MONGO_TELEMETRIA
  TO ROLE ROLE_DBT_PROYECTO_BI_TRANSPORTE_V2;

GRANT CREATE TABLE, CREATE VIEW
  ON SCHEMA PROYECTO_BI_TRANSPORTE_V2.DWH_DEV
  TO ROLE ROLE_DBT_PROYECTO_BI_TRANSPORTE_V2;
GRANT CREATE TABLE, CREATE VIEW
  ON SCHEMA PROYECTO_BI_TRANSPORTE_V2.SNAPSHOTS_DWH
  TO ROLE ROLE_DBT_PROYECTO_BI_TRANSPORTE_V2;

GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES
  ON ALL TABLES IN SCHEMA PROYECTO_BI_TRANSPORTE_V2.DWH_DEV
  TO ROLE ROLE_DBT_PROYECTO_BI_TRANSPORTE_V2;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES
  ON FUTURE TABLES IN SCHEMA PROYECTO_BI_TRANSPORTE_V2.DWH_DEV
  TO ROLE ROLE_DBT_PROYECTO_BI_TRANSPORTE_V2;

GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES
  ON ALL TABLES IN SCHEMA PROYECTO_BI_TRANSPORTE_V2.SNAPSHOTS_DWH
  TO ROLE ROLE_DBT_PROYECTO_BI_TRANSPORTE_V2;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES
  ON FUTURE TABLES IN SCHEMA PROYECTO_BI_TRANSPORTE_V2.SNAPSHOTS_DWH
  TO ROLE ROLE_DBT_PROYECTO_BI_TRANSPORTE_V2;

GRANT SELECT ON ALL VIEWS IN SCHEMA PROYECTO_BI_TRANSPORTE_V2.DWH_DEV
  TO ROLE ROLE_DBT_PROYECTO_BI_TRANSPORTE_V2;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA PROYECTO_BI_TRANSPORTE_V2.DWH_DEV
  TO ROLE ROLE_DBT_PROYECTO_BI_TRANSPORTE_V2;

GRANT CREATE STAGE, CREATE FILE FORMAT
  ON SCHEMA PROYECTO_BI_TRANSPORTE_V2.DWH_DEV
  TO ROLE ROLE_DBT_PROYECTO_BI_TRANSPORTE_V2;
GRANT CREATE STAGE, CREATE FILE FORMAT
  ON SCHEMA PROYECTO_BI_TRANSPORTE_V2.SNAPSHOTS_DWH
  TO ROLE ROLE_DBT_PROYECTO_BI_TRANSPORTE_V2;


-- =============================================================================
-- 9) ROLE BI READ
--    Solo lectura de la capa analitica
-- =============================================================================
GRANT USAGE ON SCHEMA PROYECTO_BI_TRANSPORTE_V2.DWH_DEV
  TO ROLE ROLE_BI_READ_PROYECTO_BI_TRANSPORTE_V2;
GRANT USAGE ON SCHEMA PROYECTO_BI_TRANSPORTE_V2.SNAPSHOTS_DWH
  TO ROLE ROLE_BI_READ_PROYECTO_BI_TRANSPORTE_V2;

GRANT SELECT ON ALL TABLES IN SCHEMA PROYECTO_BI_TRANSPORTE_V2.DWH_DEV
  TO ROLE ROLE_BI_READ_PROYECTO_BI_TRANSPORTE_V2;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PROYECTO_BI_TRANSPORTE_V2.DWH_DEV
  TO ROLE ROLE_BI_READ_PROYECTO_BI_TRANSPORTE_V2;
GRANT SELECT ON ALL VIEWS IN SCHEMA PROYECTO_BI_TRANSPORTE_V2.DWH_DEV
  TO ROLE ROLE_BI_READ_PROYECTO_BI_TRANSPORTE_V2;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA PROYECTO_BI_TRANSPORTE_V2.DWH_DEV
  TO ROLE ROLE_BI_READ_PROYECTO_BI_TRANSPORTE_V2;


-- =============================================================================
-- 10) USUARIOS
-- =============================================================================
CREATE USER IF NOT EXISTS USR_AIRBYTE_PROYECTO_BI_TRANSPORTE_V2
  PASSWORD = 'CambiarEstaClaveAirbyte#2026'
  DEFAULT_ROLE = ROLE_AIRBYTE_RAW_PROYECTO_BI_TRANSPORTE_V2
  DEFAULT_WAREHOUSE = WH_PROYECTO_BI_TRANSPORTE_V2
  DEFAULT_NAMESPACE = PROYECTO_BI_TRANSPORTE_V2.MYSQL_COMERCIAL
  MUST_CHANGE_PASSWORD = FALSE;

CREATE USER IF NOT EXISTS USR_DBT_PROYECTO_BI_TRANSPORTE_V2
  PASSWORD = 'CambiarEstaClaveDbt#2026'
  DEFAULT_ROLE = ROLE_DBT_PROYECTO_BI_TRANSPORTE_V2
  DEFAULT_WAREHOUSE = WH_PROYECTO_BI_TRANSPORTE_V2
  DEFAULT_NAMESPACE = PROYECTO_BI_TRANSPORTE_V2.DWH_DEV
  MUST_CHANGE_PASSWORD = FALSE;

CREATE USER IF NOT EXISTS USR_BI_PROYECTO_BI_TRANSPORTE_V2
  PASSWORD = 'CambiarEstaClaveBI#2026'
  DEFAULT_ROLE = ROLE_BI_READ_PROYECTO_BI_TRANSPORTE_V2
  DEFAULT_WAREHOUSE = WH_PROYECTO_BI_TRANSPORTE_V2
  DEFAULT_NAMESPACE = PROYECTO_BI_TRANSPORTE_V2.DWH_DEV
  MUST_CHANGE_PASSWORD = FALSE;

GRANT ROLE ROLE_AIRBYTE_RAW_PROYECTO_BI_TRANSPORTE_V2
  TO USER USR_AIRBYTE_PROYECTO_BI_TRANSPORTE_V2;
GRANT ROLE ROLE_DBT_PROYECTO_BI_TRANSPORTE_V2
  TO USER USR_DBT_PROYECTO_BI_TRANSPORTE_V2;
GRANT ROLE ROLE_BI_READ_PROYECTO_BI_TRANSPORTE_V2
  TO USER USR_BI_PROYECTO_BI_TRANSPORTE_V2;


-- =============================================================================
-- 11) NETWORK POLICY OPCIONAL
--    Reemplaza IPs/CIDR por las reales de tu entorno si quieres restringir acceso
-- =============================================================================
CREATE NETWORK POLICY IF NOT EXISTS NP_PROYECTO_BI_TRANSPORTE_V2
  ALLOWED_IP_LIST = (
    '0.0.0.0/0'
    -- Ejemplos reales:
    -- '181.115.210.10/32',
    -- '190.129.20.0/24'
  );

-- Si quieres aplicarla, descomenta estas lineas despues de reemplazar las IPs:
-- ALTER USER USR_AIRBYTE_PROYECTO_BI_TRANSPORTE_V2 SET NETWORK_POLICY = NP_PROYECTO_BI_TRANSPORTE_V2;
-- ALTER USER USR_DBT_PROYECTO_BI_TRANSPORTE_V2 SET NETWORK_POLICY = NP_PROYECTO_BI_TRANSPORTE_V2;
-- ALTER USER USR_BI_PROYECTO_BI_TRANSPORTE_V2 SET NETWORK_POLICY = NP_PROYECTO_BI_TRANSPORTE_V2;

-- Si no quieres restringir por IP, deja los usuarios sin politica:
ALTER USER USR_AIRBYTE_PROYECTO_BI_TRANSPORTE_V2 UNSET NETWORK_POLICY;
ALTER USER USR_DBT_PROYECTO_BI_TRANSPORTE_V2 UNSET NETWORK_POLICY;
ALTER USER USR_BI_PROYECTO_BI_TRANSPORTE_V2 UNSET NETWORK_POLICY;


-- =============================================================================
-- 12) VALIDACION RAPIDA
-- =============================================================================
SHOW WAREHOUSES LIKE 'WH_PROYECTO_BI_TRANSPORTE_V2';
SHOW DATABASES LIKE 'PROYECTO_BI_TRANSPORTE_V2';
SHOW SCHEMAS IN DATABASE PROYECTO_BI_TRANSPORTE_V2;
SHOW ROLES LIKE 'ROLE\\_%PROYECTO_BI_TRANSPORTE_V2';
SHOW USERS LIKE 'USR\\_%PROYECTO_BI_TRANSPORTE_V2';

SHOW GRANTS TO ROLE ROLE_AIRBYTE_RAW_PROYECTO_BI_TRANSPORTE_V2;
SHOW GRANTS TO ROLE ROLE_DBT_PROYECTO_BI_TRANSPORTE_V2;
SHOW GRANTS TO ROLE ROLE_BI_READ_PROYECTO_BI_TRANSPORTE_V2;


-- =============================================================================
-- 13) GUIA DE USO
-- =============================================================================
-- Airbyte:
--   user      = USR_AIRBYTE_PROYECTO_BI_TRANSPORTE_V2
--   role      = ROLE_AIRBYTE_RAW_PROYECTO_BI_TRANSPORTE_V2
--   warehouse = WH_PROYECTO_BI_TRANSPORTE_V2
--   database  = PROYECTO_BI_TRANSPORTE_V2
--   schemas   = MYSQL_COMERCIAL / PG_OPS / SQLSERVER_FIN / MONGO_TELEMETRIA
--
-- dbt:
--   user      = USR_DBT_PROYECTO_BI_TRANSPORTE_V2
--   role      = ROLE_DBT_PROYECTO_BI_TRANSPORTE_V2
--   warehouse = WH_PROYECTO_BI_TRANSPORTE_V2
--   database  = PROYECTO_BI_TRANSPORTE_V2
--   schema    = DWH_DEV
--
-- BI / Power BI / Lectura:
--   user      = USR_BI_PROYECTO_BI_TRANSPORTE_V2
--   role      = ROLE_BI_READ_PROYECTO_BI_TRANSPORTE_V2
--   warehouse = WH_PROYECTO_BI_TRANSPORTE_V2
--   database  = PROYECTO_BI_TRANSPORTE_V2
--   schema    = DWH_DEV
