-- Bootstrap para crear el nuevo espacio de transformaciones sin tocar DWH_DEV
-- Objetivo:
--   - mantener PROYECTO_BI_TRANSPORTE_V2.DWH_DEV intacto
--   - agregar PROYECTO_BI_TRANSPORTE_V2.DWH_DEV_CLOUD
--   - agregar PROYECTO_BI_TRANSPORTE_V2.SNAPSHOTS_DWH_CLOUD
--   - dar permisos al rol dbt para leer RAW y escribir en los nuevos schemas

-- ============================================================================
-- 0) Opcional: dar el rol dbt al usuario que ejecutara dbt/Dagster
--    Ejecutar solo si ese usuario todavia no tiene el rol.
--    Requiere SECURITYADMIN.
-- ============================================================================
USE ROLE SECURITYADMIN;

GRANT ROLE ROLE_DBT_PROYECTO_BI_TRANSPORTE_V2 TO USER VISMARKCHOQUE;

-- ============================================================================
-- 1) Crear los schemas nuevos y asegurar permisos base
--    Requiere ACCOUNTADMIN o un rol con ownership sobre database/schema.
-- ============================================================================
USE ROLE ACCOUNTADMIN;
USE WAREHOUSE WH_PROYECTO_BI_TRANSPORTE_V2;
USE DATABASE PROYECTO_BI_TRANSPORTE_V2;

CREATE SCHEMA IF NOT EXISTS DWH_DEV_CLOUD;
CREATE SCHEMA IF NOT EXISTS SNAPSHOTS_DWH_CLOUD;

GRANT USAGE ON WAREHOUSE WH_PROYECTO_BI_TRANSPORTE_V2
TO ROLE ROLE_DBT_PROYECTO_BI_TRANSPORTE_V2;

GRANT USAGE ON DATABASE PROYECTO_BI_TRANSPORTE_V2
TO ROLE ROLE_DBT_PROYECTO_BI_TRANSPORTE_V2;

-- ============================================================================
-- 2) Permisos de lectura sobre schemas RAW que usa dbt
-- ============================================================================
GRANT USAGE ON SCHEMA PROYECTO_BI_TRANSPORTE_V2."MYSQL_COMERCIAL|"
TO ROLE ROLE_DBT_PROYECTO_BI_TRANSPORTE_V2;
GRANT SELECT ON ALL TABLES IN SCHEMA PROYECTO_BI_TRANSPORTE_V2."MYSQL_COMERCIAL|"
TO ROLE ROLE_DBT_PROYECTO_BI_TRANSPORTE_V2;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PROYECTO_BI_TRANSPORTE_V2."MYSQL_COMERCIAL|"
TO ROLE ROLE_DBT_PROYECTO_BI_TRANSPORTE_V2;

GRANT USAGE ON SCHEMA PROYECTO_BI_TRANSPORTE_V2.PG_OPS
TO ROLE ROLE_DBT_PROYECTO_BI_TRANSPORTE_V2;
GRANT SELECT ON ALL TABLES IN SCHEMA PROYECTO_BI_TRANSPORTE_V2.PG_OPS
TO ROLE ROLE_DBT_PROYECTO_BI_TRANSPORTE_V2;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PROYECTO_BI_TRANSPORTE_V2.PG_OPS
TO ROLE ROLE_DBT_PROYECTO_BI_TRANSPORTE_V2;

GRANT USAGE ON SCHEMA PROYECTO_BI_TRANSPORTE_V2.SQLSERVER_FIN
TO ROLE ROLE_DBT_PROYECTO_BI_TRANSPORTE_V2;
GRANT SELECT ON ALL TABLES IN SCHEMA PROYECTO_BI_TRANSPORTE_V2.SQLSERVER_FIN
TO ROLE ROLE_DBT_PROYECTO_BI_TRANSPORTE_V2;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PROYECTO_BI_TRANSPORTE_V2.SQLSERVER_FIN
TO ROLE ROLE_DBT_PROYECTO_BI_TRANSPORTE_V2;

GRANT USAGE ON SCHEMA PROYECTO_BI_TRANSPORTE_V2.MONGO_TELEMETRIA
TO ROLE ROLE_DBT_PROYECTO_BI_TRANSPORTE_V2;
GRANT SELECT ON ALL TABLES IN SCHEMA PROYECTO_BI_TRANSPORTE_V2.MONGO_TELEMETRIA
TO ROLE ROLE_DBT_PROYECTO_BI_TRANSPORTE_V2;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PROYECTO_BI_TRANSPORTE_V2.MONGO_TELEMETRIA
TO ROLE ROLE_DBT_PROYECTO_BI_TRANSPORTE_V2;

-- ============================================================================
-- 3) Permisos de escritura en el nuevo destino cloud
-- ============================================================================
GRANT USAGE ON SCHEMA PROYECTO_BI_TRANSPORTE_V2.DWH_DEV_CLOUD
TO ROLE ROLE_DBT_PROYECTO_BI_TRANSPORTE_V2;
GRANT ALL PRIVILEGES ON SCHEMA PROYECTO_BI_TRANSPORTE_V2.DWH_DEV_CLOUD
TO ROLE ROLE_DBT_PROYECTO_BI_TRANSPORTE_V2;

GRANT USAGE ON SCHEMA PROYECTO_BI_TRANSPORTE_V2.SNAPSHOTS_DWH_CLOUD
TO ROLE ROLE_DBT_PROYECTO_BI_TRANSPORTE_V2;
GRANT ALL PRIVILEGES ON SCHEMA PROYECTO_BI_TRANSPORTE_V2.SNAPSHOTS_DWH_CLOUD
TO ROLE ROLE_DBT_PROYECTO_BI_TRANSPORTE_V2;

-- ============================================================================
-- 4) Verificaciones rapidas
-- ============================================================================
USE ROLE ROLE_DBT_PROYECTO_BI_TRANSPORTE_V2;
USE WAREHOUSE WH_PROYECTO_BI_TRANSPORTE_V2;
USE DATABASE PROYECTO_BI_TRANSPORTE_V2;
USE SCHEMA DWH_DEV_CLOUD;

SHOW SCHEMAS LIKE 'DWH_DEV_CLOUD' IN DATABASE PROYECTO_BI_TRANSPORTE_V2;
SHOW SCHEMAS LIKE 'SNAPSHOTS_DWH_CLOUD' IN DATABASE PROYECTO_BI_TRANSPORTE_V2;

SELECT CURRENT_ROLE() AS current_role, CURRENT_DATABASE() AS current_database, CURRENT_SCHEMA() AS current_schema;

SELECT COUNT(*) AS raw_cliente_n
FROM PROYECTO_BI_TRANSPORTE_V2."MYSQL_COMERCIAL|".CLIENTE;
